### ISSUE TITLE
Confusing argument p for the init command

### ISSUE THREAD

**Issue by mprangenberg** [Stefouch/sebedius-yearzero-discord-bot#107]
### Describe the Bug

I noticed, that !init is the only command where -p isn't a shortcut for -private but for -place/-init instead. This could be highly confusing for a user.
Additionally "p" without the dash can be used as a shortcut for the subcommand "previous". This adds to the confusion.

### Severity

- Medium (minor functional impact)

### Expected Behavior

I would at least expect -p to be a shortcut for -private, as in any other command that supports this argument.
Unfortunately this would be a break in the command and we would need a different shortcut for the -place argument.

What do you think @Stefouch ?

**Comment by Stefouch** [comment]
And if I remember correctly, `-h` is used to hide information, like the `-p` in other commands?

**Comment by mprangenberg** [comment]
That's right. I just did a search and it looks like the only other command with the 'hide' variant is !zonesector, there the '-p' alias is also missing. Everywhere else it's only '-private|-p', if an option like that even exists.

**Comment by Stefouch** [comment]
Closed because bot revamp. The init command will return back in a near future with better options
