### ISSUE TITLE
Extra dice append to bot response

### ISSUE THREAD

**Issue by Naith123** [Stefouch/sebedius-yearzero-discord-bot#108]
### Describe the Bug

When dice command is give, extra dice is appended to result.

### Severity
- Low (formatting issues, things that don't impact operation)

### Context

!roll 10d

on a server with the default system set to Coriolis

### To Reproduce

In channel type in command and extra dice appears.

### Expected Behavior

Extra dice does not appear. 

### Screenshots
![image](https://user-images.githubusercontent.com/24856132/115037997-fff6a700-9ec6-11eb-9de9-336ca082dfd7.png)

**Comment by Naith123** [comment]
![image](https://user-images.githubusercontent.com/24856132/115040187-13a30d00-9ec9-11eb-890c-dea12a3b2ffc.png)

We tried it again and got a 4 this time so doesn't seem like it is just appending a 6, but actually rolling an extra dice

![image](https://user-images.githubusercontent.com/24856132/115040332-3a614380-9ec9-11eb-85d5-2b9f4b1b4bd5.png)

It seems to be related to whether there is text at the end of the message but not sure why it started doing that all of a sudden.

**Comment by Naith123** [comment]
One more test actually seems to confirm it is definitely related to the appended text 
![image](https://user-images.githubusercontent.com/24856132/115040548-73011d00-9ec9-11eb-8310-73a06fc03dbd.png)

**Comment by Naith123** [comment]
![image](https://user-images.githubusercontent.com/24856132/115041201-2702a800-9eca-11eb-8a29-e0df845de75e.png)
Ok not sure what happened this time, A 1 got appended to the result.

**Comment by mprangenberg** [comment]
The Problem is that the added Text is interpreted as more dice to roll. If you want to name a roll do it with the parameter `-name` as described in the help section for the roll command https://github.com/Stefouch/sebedius-yearzero-discord-bot/wiki/%21roll 

`!roll 10d -name This is the name of the roll`

**Comment by Stefouch** [comment]
Hi @Naith123 

To add more information, `a b c d` are dice codes used by **Twilight 2000**.

To add a title to your roll, use the above examples. (If you are using the `#`, don't forget the space after it.)

**Comment by Naith123** [comment]
Thanks for the explanation.
