### ISSUE TITLE
@mention doesn't appear to work

### ISSUE THREAD

**Issue by nicholaswold** [Stefouch/sebedius-yearzero-discord-bot#124]
### Describe the Bug

Saw this happen in two places:
1. In DMs with the bot
2. On a new server

Basically doing `@Sebedius` doesn't appear to trigger any responses, while using the default prefix does.

### Severity

- Medium (minor functional impact)

Prevents easy configuration without running into conflict with other bots.

### To Reproduce

1. `@Sebedius ping`

### Expected Behavior

The readme suggests that the `@mention` should work, so I'm suspecting this is either a bug or deprecated functionality.

### Screenshots

![image](https://user-images.githubusercontent.com/1581984/128606829-cef81c5d-7d7a-40b4-aef5-11d3a01e1c14.png)

![image](https://user-images.githubusercontent.com/1581984/128606847-d59d2c04-bfa3-4e39-920c-a193ef03360b.png)

**Comment by Stefouch** [comment]
Closed because bot revamp
