### ISSUE TITLE
The One Ring 2ed (Free League) dices support

### ISSUE THREAD

**Issue by kamich** [Stefouch/sebedius-yearzero-discord-bot#130]
### Is your feature request related to a problem? Please describe.
I cannot easily roll The One Ring feat dice (d12, but on 11-> eye of sauron, but value=0, on 12-> rune of Gandalf = automatic success, but value = 10).
I cannot easily roll The One Ring feat dice combined with skill dices and favored/ill-favored rolls

### Who would use it?
The One Ring 2ed players (me and my friends for example)

### What part of the bot?
Dice roller.

### How would it work?
for The One Ring !roll d12 + 3d6
!roll TOR feat + 3skill
!roll TOR feat + 3skill weary
!roll TOR feat favored

### Why should this be added?
1. It is not working right now/difficult to re-create manually.
2. Fits into Free League game support.
3. The One Ring 2ed is just delivered :)

### Additional context
A few icons matching The One Ring dices will be nice to have.

**Comment by Stefouch** [comment]
As The One Ring is not a Year Zero Engine game, I unfortunately won't add support for it.
