### ISSUE TITLE
Remove requirement for base:

### ISSUE THREAD

**Issue by terriblyinept** [Stefouch/sebedius-yearzero-discord-bot#170]
### Feature

Sebedius, at least for Forbidden lands, requires the base: field and a value between 1 and 100. In Forbidden Lands, there are cases (such as with animals without Wits but with Scouting skill) where Base Dice are not provided or required by the system.

### Ideal solution or implementation

Don't require autofill or require the "base:" field, at least for

`/roll fbl`

**Comment by Stefouch** [comment]
I am looking at a solution for this issue.

Meanwhile, you can use the new command `/rolla` which has all arguments of all roll commands from all games, but none is required.

E.g: `/rolla skill:7 game:fbl` (the last argument `game:fbl` can be omitted if you set the default game for your server with `/conf`)
