### ISSUE TITLE
Language test is broken

### ISSUE THREAD

**Issue by mprangenberg** [Stefouch/sebedius-yearzero-discord-bot#189]
### Which command was used?

Pull request

### Issue Description

See PR #188 .
The following problem occured:
> AssertionError: de/table-bladerunner-crit-crushing: title case name of 1: expected 'Zähne ausgeschlagen' to match /^(?:[A-ZÄÅÖ][^\s]*\s?\(?)+$/

The problem here is, that in some translations the words don't always start with uppercase letters.

Solution:
Remove the necessity to have uppercase letters, maybe just for the first word: `/^(?:[^\s]*\s?\(?)+$/`
Also, if we want to demand the first word to have an uppercase letter, then the match should be done with \p{Lu} instead. This should match all uppercase unicode letters: `/^\p{Lu}(?:[^\s]*\s?\(?)+$/`

### Priority this issue should have?

High (a broken feature, major functional impact)

### Bot's Permissions

- [X] I confirm that I checked the bot's permissions

**Comment by Stefouch** [comment]
> The problem here is, that in some translations the words don't always start with uppercase letters.
Is it an mistake to use title case for all words in a title sentence in German?
I see it in use in some movie titles in German.

**Comment by mprangenberg** [comment]
That's a stylistic choice. But usually you don't use all uppercase words in titles. Even in the official translations the case varies...

**Comment by mprangenberg** [comment]
Also, just noticed: In the german translation of the vaesen crit tables, the effects don't end with punctuations:
> AssertionError: de/table-vaesen-crit-damage: punctuation end of effect of 1: expected 'Gebrechen: Hinken, `BEWEGLICHKEIT` -1' to match /\.\)?\*?$/gm
Should i fix that in the table or should we drop that rule?

**Comment by Stefouch** [comment]
> end with punctuations

I would like to keep consistency between all games and all injuries' effects should end with a punctuation.

> That's a stylistic choice. But usually you don't use all uppercase words in titles. Even in the official translations the case varies...

In the core books, the title-casing each word of the name of the injuries does not make sense since they are in a table.

But here, a single crit is displayed and its name becomes the title of the embed message, like the title of a movie. I would like also to have some consistency here. But if you think it's not a good idea because it's wrong in other languages or it's a bad esthetic choice, then I'm OK to cut this regex rule.

**Comment by mprangenberg** [comment]
The punctuation is a minor inconvenience, so no problem there.

The title casing makes no sense in german, though. At least according to the official german spelling rules.
Simplified, the rule is that words only start uppercase at the beginning of a sentence or if it's a name or has an article.

**Comment by mprangenberg** [comment]
But, if you want it to look a certain way, then that is acceptable, too. Although there could possibly be similar discussion if there are more languages incoming.

Nevertheless the test should at least be changed to include all possible uppercase letters as i pointed in my initial post.

**Comment by mprangenberg** [comment]
Alright, i went through the tables again. Some names can be adjusted to both fit your rule and the correct german spelling.
Others unfortunately can't and just look wrong that way 🙈

Also, regarding your movie title argument: usually movie titles are like i described above or complete upper case.
For example with the Lord of the rings the title would be either DER HERR DER RINGE or Der Herr der Ringe, but never Der Herr Der Ringe. To a german speaker that looks like there should be an emphasis on the article when it is not.

**Comment by Stefouch** [comment]
> Nevertheless the test should at least be changed to include all possible uppercase letters as i pointed out in my initial post.

Unfortunately, `\p{Lu}` does not seem compatible in Javascript :-(

**Comment by mprangenberg** [comment]
Thats's too bad. Then `[A-ZÁÀÂÄÃÅÇÉÈÊËÍÌÎÏÑÓÒÔÖÕÚÙÛÜÝŸÆŒ]` should be the way to go...
