### ISSUE TITLE
Roll interaction seems broken

### ISSUE THREAD

**Issue by mprangenberg** [Stefouch/sebedius-yearzero-discord-bot#195]
### Which command was used?

any /roll

### Issue Description

Interaction with the roll command seems broken. Whenever you click the push or confirm buttons it takes a moment and then says "interaction failed"
![image](https://user-images.githubusercontent.com/19757902/229211335-644a7d80-c16b-4136-aa91-117007c61ce4.png)

### Priority this issue should have?

High (a broken feature, major functional impact)

### Bot's Permissions

- [X] I confirm that I checked the bot's permissions

**Comment by mprangenberg** [comment]
Now rolls are sometimes completely broken:
![image](https://user-images.githubusercontent.com/19757902/229222152-72de9416-5014-4817-a91d-064c16064242.png)

**Comment by Stefouch** [comment]
I'm investigating..

Le ven. 31 mars 2023 à 22:23, mprangenberg ***@***.***> a
écrit :

**Comment by Cussa** [comment]
Hello @Stefouch can you check if there was any new change that broke this? Whenever I try to push a roll, it says that "This interaction failed".
<img width="461" alt="Screenshot 2023-10-24 at 19 56 58" src="https://github.com/Stefouch/sebedius-yearzero-discord-bot/assets/912710/91a3f8db-02b6-4303-b908-bcf26cbd736b">

**Comment by Stefouch** [comment]
Hi @Cussa ,
This issue is probably caused by a permission issue. Check that the bot has all needed permissions in the server AND in that channel.

**Comment by Cussa** [comment]
Thanks @Stefouch ! The issue was that the bot was not in the channel, only in the server.
