### ISSUE TITLE
Pushing Roll Command fails

### ISSUE THREAD

**Issue by DarthCaustic** [Stefouch/sebedius-yearzero-discord-bot#207]
### Which command was used?

/roll alien dice:8 stress:2

### Issue Description

Made basic skill roll. Roll functioned as normal. Attempted to Push the roll for more successes, Push function failed. 
![Screenshot_20231219_085941_Discord](https://github.com/Stefouch/sebedius-yearzero-discord-bot/assets/154359253/93e10d25-501e-4615-9f71-cbfe0d77b19d)

### Priority this issue should have?

High (a broken feature, major functional impact)

### Bot's Permissions

- [X] I confirm that I checked the bot's permissions

**Comment by Stefouch** [comment]
This is probably a permission issue.
Check that the server AND the channel have all needed permissions for the bot.

See also: #195
