### ISSUE TITLE
Bot shows up as offline and no functions are working

### ISSUE THREAD

**Issue by DarthCaustic** [Stefouch/sebedius-yearzero-discord-bot#208]
### Which command was used?

/roll alien

### Issue Description

No dice commands work. a message pops up of "The application did not respond" this happened suddenly as the bot has been working fine until today. Also the bot appears as "Offline" under the memeber list which is not what it usually appears as. 
![Screenshot (143)](https://github.com/Stefouch/sebedius-yearzero-discord-bot/assets/154359253/e7d339ba-abd2-4802-a213-b64b43e67adf)
![Screenshot (143)2](https://github.com/Stefouch/sebedius-yearzero-discord-bot/assets/154359253/ca141e00-d823-46be-a399-fa29fef6c323)

### Priority this issue should have?

High (a broken feature, major functional impact)

### Bot's Permissions

- [X] I confirm that I checked the bot's permissions

**Comment by Olovhk** [comment]
I was using the bot yesterday for our session of Forbidden Lands and I can confirm that the exact same thing happened to me.

**Comment by voidandpulse** [comment]
Encountered this today. Worked fine after initial setup, but when I came back 2 hours later I encountered this issue.

**Comment by pepato** [comment]
Same here. Since a couple of weeks, Sebedius is not responding. Tried to uninstall then reinstall, nothing.

**Comment by emvee81** [comment]
Same here. It worked perfectly less than month ago.. Now I have the same error msg as OP above.

**Comment by DarthCaustic** [comment]
I will say that it seemed to come back online about 5 days ago, lasted a couple hours and has been offline again since. Not sure if the host needs a reboot

**Comment by Stefouch** [comment]
Hi there!

I have investigated and found the origin of the issue.
The bot reached >2500 Discord servers and Discord actually does not allow more unless some code changes for supporting multi-threading (sharding). This cause the bot to randomly disconnect from certain Discord servers. I'm working on a fix.

This will probably mean more costs from the hosting server that runs the bot. I hope it won't be too much.

**Comment by Alsageek67** [comment]
In a way, its a celebration, your work is effectively recognized and is widely used.
Congratulations are required, bravo.

**Comment by pepato** [comment]
Thanks for finding the issue!
My humble proposal would be to scorporate the different games into separate bots. So if I play Vaesen and you play Alien, they would not count together on the total of servers.
But I cannot appreciate enough the work you're doing. Thanks!

**Comment by emvee81** [comment]
I just tested it in two different discord servers and it works correctly again

**Comment by Stefouch** [comment]
> I just tested it in two different discord servers and it works correctly again

Yes disconnections are random.

Next update should fix this issue.

**Comment by Stefouch** [comment]
Should be good now!

**Comment by pepato** [comment]
Just reinstalled on my Vaesen server. It works fine now!
