### ISSUE TITLE
Vaesen Crit Table

### ISSUE THREAD

**Issue by nipunG314** [Stefouch/sebedius-yearzero-discord-bot#64]
The vaesen crit table is missing from the database. Is it simply missing or is there another reason(copyright, etc...)?

I don't mind adding it to the database myself if it is simply missing. As long as you can tell me where to add it.

**Comment by Stefouch** [comment]
Hi @nipunG314 ,

It is simply missing. I didn't have the time to add them to the bot yet.

If you have a few hours free to do it, your contribution is more than welcome!

Take a look in the `/gamedata/crits/` folder. It's how the crits are encoded, in `.cls` files.

**Comment by Naith123** [comment]
Looking at helping add the Coriolis one, looking at https://github.com/Stefouch/sebedius-myz-discord-bot/tree/master/gamedata/crits

I see lots of CSV files but no .cls files. Just want to sanity-check your message in case I am missing something.

**Comment by mprangenberg** [comment]
Yes, can confirm, that they are csv-files. I also added the Coriolis crits in my pull request: https://github.com/Stefouch/sebedius-myz-discord-bot/pull/81/files#diff-b0dcc6931aa2b8b5f95d830cb6cb97eb8b6db050229749a7e677351c40e88e0d
Maybe you can do a quality check?
